<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Promo
 */
?>
<?php /** @var \Amasty\Promo\Block\Banner $block */?>
<?php /** @var \Amasty\Promo\Model\Rule $_rule */?>
<?php foreach($block->getValidRules() as $_rule) :?>
    <?php if ($block->getDescription($_rule) || $block->getImage($_rule) || $block->isShowGiftImages($_rule)):?>
        <div>
            <?php if ($block->getDescription($_rule)): ?>
                <div class="ampromo-desc">
                    <?= $block->getPageTemplateProcessor()->filter($block->getDescription($_rule)); ?>
                </div>
            <?php endif; ?>
            <?php $img = $block->getImage($_rule); ?>
            <?php if ($img) :?>
                <p class="ampromo-img">
                    <a href="<?= $block->escapeUrl($block->getLink($_rule));?>" title="<?= $block->escapeHtml($block->getHoverText($_rule)) ?>">
                        <img src="<?= $img;?>"
                             alt="<?= $block->escapeHtml($block->getAlt($_rule)) ?>"
                             title="<?= $block->escapeHtml($block->getHoverText($_rule)) ?>" />
                    </a>
                </p>
            <?php endif; ?>
            <?php if ($block->isShowGiftImages($_rule)) :?>
                <ul class="ampromo-gift">
                    <?php /** @var \Magento\Catalog\Model\Product $product */?>
                    <?php foreach($block->getProducts($_rule) as $product): ?>
                        <?php
                            $product->getAttributeRawValue($product->getId(), $block->getAttributeHeader(), 1);
                            $id = uniqid("ampromo-gift-img-");
                        ?>
                        <li>
                            <a class="product-image" href="<?= $block->escapeUrl($product->getProductUrl())?>">
                                <img class="ampromo-banner-<?= $block->escapeHtml($block->getPosition())?>-img"
                                     id="<?= $id;?>"
                                     alt="<?= $block->escapeHtml('Product Image') ?>"
                                     width="<?= $block->escapeHtml($block->getWidth());?>"
                                     height="<?= $block->escapeHtml($block->getHeight());?>"
                                     src="<?= $block->escapeUrl($block->getImageHelper()->init($product, 'mini_cart_product_thumbnail')
                                        ->keepFrame(false)
                                        ->constrainOnly(true)
                                        ->resize($block->getWidth())
                                        ->getUrl());
                                ?>"/>
                                <div id="<?= $id;?>-data" style="display: none;">
                                    <div class="ampromo-product-name"><?= $product->getResource()->getAttribute($block->
                                        getAttributeHeader())->getFrontend()->getValue($product);?>
                                    </div>
                                    <div class="ampromo-short-description"><?= $product->getResource()->
                                        getAttribute($block->getAttributeDescription())->getFrontend()->getValue($product);?>
                                    </div>
                                </div>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    <?php endif;?>
<?php endforeach; ?>
<script>
    require([
        'tooltip',
        'jquery'
    ], function(tooltip, $) {
        if( !/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
            $('.ampromo-banner-<?= $block->getPosition()?>-img').each(function(key, image){
                tooltip({
                    tooltipClass: "ampromo-banner-tooltip",
                    content: function () {
                        return $('#' + this.id + '-data').html();
                    },
                }, image);
            });
        }
    });
</script>

