<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Preorder
 */
?>
<?php
/** @var \Amasty\Preorder\Block\Product\View\Preorder\ProductDefault $block */
if (!$block->canShowBlock()) {
    return;
}
?>
<script type="text/javascript">
    require(['jquery', 'Amasty_Preorder/js/product/preorder'], function ($) {
        $widget = $.mage.amastyPreorder({
            availabilityElement: '<?= $block->getPreorderNotePosition(); ?>',
            preOrderNote: '<?= $block->getPreorderNote(); ?>',
            addToCartLabel: '<?= $block->getCartLabel(); ?>'
        });
        $widget.enable();
    });
</script>
