<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Preorder
 */
?>
<?php /**
 * @var $block \Amasty\Preorder\Block\Product\ListProduct\Preorder
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Amasty_Preorder/js/product/preorder_list": {
                "jsonConfig" : <?= $block->generateJsonConfig(); ?>
            }
        }
    }
</script>
